#!/usr/bin/env python3
"""Regenerate src/theme_palettes.rs from the T3 Code theme definitions.

Vireo's appearance themes (Settings -> Appearance -> Theme) are the palettes
T3 Code ships, adapted to libadwaita's colour roles and renamed for Vireo
(see NAMES below). The upstream palettes live in a TypeScript source and are
written in OKLCH; this script converts them to sRGB hex, which is what GTK's
named colours and the reader documents both want.

Usage:
    git clone --depth 1 https://github.com/pingdotgg/t3code /tmp/t3code
    tools/gen-themes.py /tmp/t3code

T3 Code is MIT-licensed (Copyright (c) 2026 T3 Tools Inc.); the generated
file carries that notice.
"""

import math
import re
import sys
from pathlib import Path

# Vireo's own name for each upstream palette: its id, as saved in
# privacy.toml, and the name the picker shows. An upstream theme missing from
# here is not bundled -- T3 Code's own default look is one product's house
# style rather than a theme to choose, so Vireo does not carry it.
NAMES = {
    "t3-chat": ("rose", "Rose"),
    "grove": ("forest", "Forest"),
    "ocean": ("tidal", "Tidal"),
    "ember": ("earth", "Earth"),
    "iris": ("midnight", "Midnight"),
}

# The roles Vireo maps onto libadwaita colours (see src/theme.rs). Upstream
# carries more (terminal, message actions); those have no Vireo counterpart.
ROLES = [
    "canvas", "chrome", "toolbar", "toolbarForeground", "toolbarBorder",
    "toolbarControl", "toolbarControlForeground", "toolbarControlHover",
    "surface", "surfaceRaised", "surfaceOverlay", "text", "textMuted",
    "border", "input", "focus", "accent", "accentForeground", "secondary",
    "secondaryForeground", "muted", "mutedForeground", "placeholder",
    "error", "errorForeground", "errorSurface", "warning", "warningForeground",
    "warningSurface", "accentSurface", "accentSurfaceForeground",
    "messageSurface", "codeBackground", "codeForeground", "sidebar",
    "sidebarForeground", "sidebarMutedForeground", "sidebarControlSurface",
    "sidebarRowHover", "sidebarRowActive", "sidebarRowSelected", "sidebarBorder",
]


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def oklch_to_hex(lightness: float, chroma: float, hue: float) -> str:
    """OKLCH -> sRGB hex, clipped to the gamut (these palettes sit inside it)."""
    rad = math.radians(hue)
    a = chroma * math.cos(rad)
    b = chroma * math.sin(rad)
    l_ = lightness + 0.3963377774 * a + 0.2158037573 * b
    m_ = lightness - 0.1055613458 * a - 0.0638541728 * b
    s_ = lightness - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    red = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    green = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    blue = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s

    def encode(value: float) -> int:
        value = max(0.0, min(1.0, value))
        value = 12.92 * value if value <= 0.0031308 else 1.055 * value ** (1 / 2.4) - 0.055
        return max(0, min(255, round(value * 255)))

    return "#%02x%02x%02x" % (encode(red), encode(green), encode(blue))


def to_hex(value: str) -> str:
    value = value.strip()
    if value.startswith("#"):
        return value.lower()
    match = re.match(r"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.-]+)\s*\)$", value)
    if not match:
        raise SystemExit(f"unhandled colour: {value}")
    return oklch_to_hex(*(float(g) for g in match.groups()))


def parse_colors(block: str) -> dict:
    return {k: to_hex(v) for k, v in re.findall(r'(\w+):\s*"([^"]+)"', block)}


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    repo = Path(sys.argv[1])
    shared = (repo / "packages/shared/src/themePalettes.ts").read_text()

    themes = []
    for match in re.finditer(r"export const \w+_THEME: ThemeDefinition = \{(.*?)\n\};", shared, re.S):
        body = match.group(1)
        upstream = re.search(r'id:\s*"([^"]+)"', body).group(1)
        if upstream not in NAMES:
            continue
        theme_id, label = NAMES[upstream]
        themes.append({
            "id": theme_id,
            "label": label,
            # Every built-in is authored light, with dark as its variant.
            "light": parse_colors(re.search(r"\n  colors: \{(.*?)\n  \},", body, re.S).group(1)),
            "dark": parse_colors(re.search(r"\n    dark: \{(.*?)\n    \},", body, re.S).group(1)),
        })

    out = [
        "//! The built-in theme palettes, generated by `tools/gen-themes.py`.",
        "//!",
        "//! The colours are T3 Code's theme library (MIT, Copyright (c) 2026 T3",
        "//! Tools Inc.), converted from OKLCH to sRGB hex and renamed for Vireo.",
        "//! `theme.rs` maps them onto libadwaita's colour roles. Edit the",
        "//! generator, not this file.",
        "",
        "use crate::theme::{Palette, Theme};",
        "",
    ]
    for theme in themes:
        const = theme["id"].replace("-", "_").upper()
        out.append(f'pub const {const}: Theme = Theme {{')
        out.append(f'    id: "{theme["id"]}",')
        out.append(f'    label: "{theme["label"]}",')
        for variant in ("light", "dark"):
            out.append(f"    {variant}: Palette {{")
            for role in ROLES:
                out.append(f'        {snake(role)}: "{theme[variant][role]}",')
            out.append("    },")
        out.append("};")
        out.append("")
    out.append("/// Every bundled theme, in the order the picker shows them.")
    out.append("pub const THEMES: &[Theme] = &[")
    for theme in themes:
        out.append(f'    {theme["id"].replace("-", "_").upper()},')
    out.append("];")
    out.append("")

    dest = Path(__file__).resolve().parent.parent / "src/theme_palettes.rs"
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({len(themes)} themes)")


if __name__ == "__main__":
    main()
